# Generated by Django 5.2.9 on 2026-01-14 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentGallery",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("document", models.FileField(upload_to="gallery/documents/")),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Document Gallery",
                "verbose_name_plural": "Document Galleries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoGallery",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(upload_to="gallery/photos/")),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Photo Gallery",
                "verbose_name_plural": "Photo Galleries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoGallery",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("video_url", models.URLField(help_text="YouTube or Vimeo link")),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Video Gallery",
                "verbose_name_plural": "Video Galleries",
                "ordering": ["-created_at"],
            },
        ),
    ]
