# Generated by Django 5.2.9 on 2026-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentgallery",
            options={
                "ordering": ["-order"],
                "verbose_name": "Document Gallery",
                "verbose_name_plural": "Document Galleries",
            },
        ),
        migrations.AlterModelOptions(
            name="photogallery",
            options={
                "ordering": ["-order"],
                "verbose_name": "Photo Gallery",
                "verbose_name_plural": "Photo Galleries",
            },
        ),
        migrations.AlterModelOptions(
            name="videogallery",
            options={
                "ordering": ["-order"],
                "verbose_name": "Video Gallery",
                "verbose_name_plural": "Video Galleries",
            },
        ),
        migrations.AddField(
            model_name="documentgallery",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="lower numbers show first"
            ),
        ),
        migrations.AddField(
            model_name="photogallery",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="lower numbers show first"
            ),
        ),
        migrations.AddField(
            model_name="videogallery",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="lower numbers show first"
            ),
        ),
    ]
