# Generated by Django 5.2.9 on 2026-01-14 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebSetting",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(max_length=200)),
                ("site_title", models.CharField(max_length=200)),
                (
                    "site_logo",
                    models.ImageField(blank=True, null=True, upload_to="site/logo/"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_primary", models.CharField(max_length=20)),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="Bangladesh", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("google_map_embed_url", models.TextField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "office_open_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_close_time",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("footer_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
