"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = f"'{config('SECRET_KEY')}'"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)
PRODUCTION = config("PRODUCTION", default=False, cast=bool)

ALLOWED_HOSTS = ["*", "regaliabd.com"]


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://regaliabd.com/",
] 

# Application definition
# Application definition
CUSTOM_APPS = [ 
    "apps.pages",
    "apps.contacts",
    "apps.base",
    "apps.websettings",
    "apps.projects",
    "apps.galleries",
    "apps.faqs"
]

INSTALLED_LIBRARY = [
    "rest_framework",
    "drf_spectacular",
]

INSTALLED_APPS = (
    [
        'jazzmin',
        'corsheaders',
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
    ]
    +   INSTALLED_LIBRARY
    +   CUSTOM_APPS
)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.common.CommonMiddleware',

    # Static files (CSS,JS,images) when using Daphne or any ASGI server, because they don’t serve static files by default. 
    # After adding this middleware, remember to run: `python manage.py collectstatic 
    'whitenoise.middleware.WhiteNoiseMiddleware',

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
if PRODUCTION:
    DATABASES = {
        "default": {
            "ENGINE": config("DB_ENGINE", cast=str),
            "NAME": config("DB_NAME", cast=str),
            "USER": config("DB_USER", cast=str),
            "PASSWORD": config("DB_PASSWORD", cast=str),
            "HOST": config("DB_HOST", cast=str),
            "PORT": config("DB_PORT", cast=int),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JS, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = []  # Add custom static directories here if needed
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # for collectstatic in production

# Media files (user-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Real State",
    "DESCRIPTION": "This project is for Real State.",
    "VERSION": "1.0.0",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "docExpansion": "none",
        # To prevent schema to be appeared uncomment the following
        # 'defaultModelsExpandDepth': -1,
    },
    "DEFAULT_AUTO_SCHEMA": "drf_spectacular.openapi.AutoSchema",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PUBLIC": True,
    "USE_SESSION_AUTH": False,
    "REDUCER": "drf_spectacular.reducing.RouterDepthReducer",
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_DIST": "https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest",
    "SWAGGER_UI_FAVICON_HREF": STATIC_URL + "images/api.ico",
    "DEFAULT_FIELD_INSPECTORS": [
        "drf_spectacular.inspectors.CamelCaseJSONFilter",
        "drf_spectacular.inspectors.InlineSerializerInspector",
        "drf_spectacular.inspectors.RelatedFieldInspector",
        "drf_spectacular.inspectors.ChoiceFieldInspector",
        "drf_spectacular.inspectors.FileFieldInspector",
        "drf_spectacular.inspectors.DictFieldInspector",
        "drf_spectacular.inspectors.SimpleFieldInspector",
        "drf_spectacular.inspectors.StringDefaultFieldInspector",
    ],
}
