# Generated by Django 5.2.9 on 2026-01-14 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about_us", "About Us"),
                            ("our_projects", "Our Projects"),
                            ("galery", "Galery"),
                            ("faq", "FAQ"),
                            ("contact_us", "Contact Us"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Write here a title of the page!", max_length=150
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Write here description of the page!"),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Write here a short tag of the page!",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload slider image", upload_to="slider/"
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Write here a heading for the slider!", max_length=150
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Write here description for the slider!"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Write here a short tag for the slider!",
                        max_length=50,
                    ),
                ),
                (
                    "button_one_name",
                    models.CharField(
                        blank=True,
                        help_text="Write first button name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "button_one_link",
                    models.URLField(
                        blank=True, help_text="Write first button link", null=True
                    ),
                ),
                (
                    "button_two_name",
                    models.CharField(
                        blank=True,
                        help_text="Write second button name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "button_two_link",
                    models.URLField(
                        blank=True, help_text="Write second button link", null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Slider order, lower numbers show first"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.page"
                    ),
                ),
            ],
            options={
                "verbose_name": "Slider Image",
                "verbose_name_plural": "Slider Images",
                "ordering": ["order"],
            },
        ),
    ]
